/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.yavuz.yipsc.gui;

import com.yavuz.yipsc.utils.CCompiler;
import com.yavuz.yipsc.utils.Tokenizer;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.imageio.stream.ImageInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author codegenius
 */
public class MainUI extends javax.swing.JFrame {
    
     private String fileAsString;
     private String filePath;
     private CCompiler cCompiler;

    /**
     * Creates new form MainUI
     */
    public MainUI() throws IOException {
        initComponents(); 
        cCompiler = new CCompiler();
                      
     // ImageIcon ii = ImageIcon(this.getClass().getResource("/resources/appIcon.png"));

        BufferedImage  image  = ImageIO.read(new File("src/resources/appIcon.png"));
        final List<Image> icons = new ArrayList<Image>();
        icons.add(image);
        icons.add(image);
        
       JFrame mainFrame = (JFrame) getFrames()[0];
       mainFrame.setIconImages(icons);
       mainFrame.setVisible(true);
       
       
       
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cCodeTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        mipsCodeTextArea = new javax.swing.JTextArea();
        explanationLabel = new javax.swing.JLabel();
        uploadCodeBtn = new javax.swing.JButton();
        verifyCodeBtn = new javax.swing.JButton();
        compileCodeBtn = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();
        infoInputLabel = new javax.swing.JLabel();
        Tokenize = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YIPSC");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setLocation(new java.awt.Point(100, 100));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setPreferredSize(new java.awt.Dimension(1000, 800));

        cCodeTextArea.setColumns(20);
        cCodeTextArea.setRows(5);
        jScrollPane1.setViewportView(cCodeTextArea);

        mipsCodeTextArea.setColumns(20);
        mipsCodeTextArea.setRows(5);
        jScrollPane2.setViewportView(mipsCodeTextArea);

        explanationLabel.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        explanationLabel.setText("Copy/Paste or Upload the C code from file here.");

        uploadCodeBtn.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        uploadCodeBtn.setText("Upload Code");
        uploadCodeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadCodeBtnActionPerformed(evt);
            }
        });

        verifyCodeBtn.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        verifyCodeBtn.setText("Verify");
        verifyCodeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyCodeBtnActionPerformed(evt);
            }
        });

        compileCodeBtn.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        compileCodeBtn.setText("Compile!");
        compileCodeBtn.setActionCommand("Compile");
        compileCodeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compileCodeBtnActionPerformed(evt);
            }
        });

        infoLabel.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        infoLabel.setText("Info:");

        infoInputLabel.setText("Program started.");

        Tokenize.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        Tokenize.setText("Tokenize");
        Tokenize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TokenizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(infoInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(explanationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(128, 128, 128)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(uploadCodeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(37, 37, 37)
                                .addComponent(verifyCodeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(54, 54, 54)
                                .addComponent(Tokenize)
                                .addGap(53, 53, 53)
                                .addComponent(compileCodeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(explanationLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(uploadCodeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(verifyCodeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(compileCodeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tokenize)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(infoLabel)
                .addGap(1, 1, 1)
                .addComponent(infoInputLabel)
                .addContainerGap())
        );

        uploadCodeBtn.getAccessibleContext().setAccessibleName("UploadCodeBtn");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void uploadCodeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadCodeBtnActionPerformed
       JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

       FileNameExtensionFilter filter = new FileNameExtensionFilter("C or CPP FILES", "c","cpp");

                jfc.setDialogTitle("Please choose C file to compile");
                jfc.setFileFilter(filter);
		int returnValue = jfc.showOpenDialog(null);
		// int returnValue = jfc.showSaveDialog(null);

		if (returnValue == JFileChooser.APPROVE_OPTION) {
			File selectedFile = jfc.getSelectedFile();
			System.out.println(selectedFile.getAbsolutePath());
                        filePath = selectedFile.getAbsolutePath();
                        
           try {
               InputStream is = new FileInputStream(selectedFile);
               BufferedReader buf = new BufferedReader(new InputStreamReader(is));

               String line = buf.readLine();
               StringBuilder sb = new StringBuilder(); 
               while(line != null){ 
                   sb.append(line).append("\n"); 
                   line = buf.readLine(); 
               }
               fileAsString = sb.toString();
               
               System.out.println("file:\n" + fileAsString);
     
               
               cCodeTextArea.setText(fileAsString);

           } catch (FileNotFoundException ex) {
               Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
           } catch (IOException ex) {
               Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
           }
                        
        
		}
    }//GEN-LAST:event_uploadCodeBtnActionPerformed

    private void verifyCodeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyCodeBtnActionPerformed
        // TODO add your handling code here:
       /// infoInputLabel.setText("Code verifying is not supported for now.");
        //infoInputLabel.setForeground(Color.red);
        
        boolean result = cCompiler.compileCFile(filePath);
        
        System.out.println("RESULT :" + result);
        if(result) {
            infoInputLabel.setText("Code compilation successful!");
            infoInputLabel.setForeground(Color.BLUE);
            Font f = infoInputLabel.getFont();
            infoInputLabel.setFont(f.deriveFont(f.getStyle() | Font.BOLD));
        } else {
            infoInputLabel.setText("Code compilation failure. Please check your code.");
            infoInputLabel.setForeground(Color.RED);
            Font f = infoInputLabel.getFont();
            infoInputLabel.setFont(f.deriveFont(f.getStyle() | Font.BOLD));
        }
            
    }//GEN-LAST:event_verifyCodeBtnActionPerformed

    private void compileCodeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compileCodeBtnActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_compileCodeBtnActionPerformed

    private void TokenizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TokenizeActionPerformed
        // TODO add your handling code here:
        
        Tokenizer mTokenizer = new Tokenizer(fileAsString);
        
       cCodeTextArea.setText(mTokenizer.reduceBlanksToOne());
       cCodeTextArea.setText(mTokenizer.removeIncludesAndComments());
       
       mTokenizer.parseIntegerVariables();
       
       mTokenizer.parseOperations();
         
    }//GEN-LAST:event_TokenizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws MalformedURLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Tokenize;
    private javax.swing.JTextArea cCodeTextArea;
    private javax.swing.JButton compileCodeBtn;
    private javax.swing.JLabel explanationLabel;
    private javax.swing.JLabel infoInputLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea mipsCodeTextArea;
    private javax.swing.JButton uploadCodeBtn;
    private javax.swing.JButton verifyCodeBtn;
    // End of variables declaration//GEN-END:variables
}
