/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.yavuz.yipsc.gui;

import com.yavuz.yipsc.asm.Assembly;
import com.yavuz.yipsc.lexer.LexInter;
import com.yavuz.yipsc.lexer.Lexer;
import com.yavuz.yipsc.parser.Parser;
import com.yavuz.yipsc.utils.CCompiler;
import com.yavuz.yipsc.utils.Tokenizer;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.imageio.stream.ImageInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author codegenius
 */
public class MainUI extends javax.swing.JFrame {

    private static final String TEMP_FILE_NAME = "temp.c";
    private String fileAsString;
    private String filePath;
    private CCompiler cCompiler;

    /**
     * Creates new form MainUI
     */
    public MainUI() throws IOException {
        initComponents();
        cCompiler = new CCompiler();

        // ImageIcon ii = ImageIcon(this.getClass().getResource("/resources/appIcon.png"));
        BufferedImage image = ImageIO.read(new File("src/resources/appIcon.png"));
        final List<Image> icons = new ArrayList<Image>();
        icons.add(image);
        icons.add(image);

        JFrame mainFrame = (JFrame) getFrames()[0];
        mainFrame.setIconImages(icons);
        mainFrame.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cCodeTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        mipsCodeTextArea = new javax.swing.JTextArea();
        explanationLabel = new javax.swing.JLabel();
        uploadCodeBtn = new javax.swing.JButton();
        verifyCodeBtn = new javax.swing.JButton();
        compileCodeBtn = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();
        infoInputLabel = new javax.swing.JLabel();
        Tokenize = new javax.swing.JButton();
        clearAllBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YIPSC");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setLocation(new java.awt.Point(100, 100));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);

        cCodeTextArea.setColumns(20);
        cCodeTextArea.setRows(5);
        jScrollPane1.setViewportView(cCodeTextArea);

        mipsCodeTextArea.setColumns(20);
        mipsCodeTextArea.setRows(5);
        jScrollPane2.setViewportView(mipsCodeTextArea);

        explanationLabel.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        explanationLabel.setText("Copy/Paste or Upload the C code from file here.");

        uploadCodeBtn.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        uploadCodeBtn.setText("Upload Code");
        uploadCodeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadCodeBtnActionPerformed(evt);
            }
        });

        verifyCodeBtn.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        verifyCodeBtn.setText("Verify");
        verifyCodeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyCodeBtnActionPerformed(evt);
            }
        });

        compileCodeBtn.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        compileCodeBtn.setText("Compile!");
        compileCodeBtn.setActionCommand("Compile");
        compileCodeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compileCodeBtnActionPerformed(evt);
            }
        });

        infoLabel.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        infoLabel.setText("Info:");

        infoInputLabel.setText("Program started.");

        Tokenize.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        Tokenize.setText("Tokenize");
        Tokenize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TokenizeActionPerformed(evt);
            }
        });

        clearAllBtn.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        clearAllBtn.setText("Clear");
        clearAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel1.setText("MIPS Assembly Output");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(infoInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 23, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(explanationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(111, 111, 111)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(verifyCodeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tokenize, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(compileCodeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clearAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uploadCodeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(explanationLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uploadCodeBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verifyCodeBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tokenize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compileCodeBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearAllBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(infoLabel)
                .addGap(1, 1, 1)
                .addComponent(infoInputLabel)
                .addContainerGap())
        );

        uploadCodeBtn.getAccessibleContext().setAccessibleName("UploadCodeBtn");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void uploadCodeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadCodeBtnActionPerformed
        JFileChooser jfc = new JFileChooser(".");

        FileNameExtensionFilter filter = new FileNameExtensionFilter("C or CPP FILES", "c", "cpp");

        jfc.setDialogTitle("Please choose C file to compile");
        jfc.setFileFilter(filter);
        int returnValue = jfc.showOpenDialog(null);
        // int returnValue = jfc.showSaveDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            System.out.println(selectedFile.getAbsolutePath());
            filePath = selectedFile.getAbsolutePath();

            try {
                InputStream is = new FileInputStream(selectedFile);
                BufferedReader buf = new BufferedReader(new InputStreamReader(is));

                String line = buf.readLine();
                StringBuilder sb = new StringBuilder();
                while (line != null) {
                    sb.append(line).append("\n");
                    line = buf.readLine();
                }
                fileAsString = sb.toString();

                System.out.println("file:\n" + fileAsString);

                cCodeTextArea.setText(fileAsString);

            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_uploadCodeBtnActionPerformed

    private void verifyCodeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyCodeBtnActionPerformed

        if (cCodeTextArea != null && !cCodeTextArea.getText().isEmpty()) {
            try {
                try ( // TODO add your handling code here:
                /// infoInputLabel.setText("Code verifying is not supported for now.");
                //infoInputLabel.setForeground(Color.red);
                // create a temporary file here.
                    PrintWriter saveOutput = new PrintWriter(TEMP_FILE_NAME)) {
                    System.out.println("cCodeArea:\n"+ cCodeTextArea.getText());
                    saveOutput.print(cCodeTextArea.getText());
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
            }

            boolean result = cCompiler.compileCFile(TEMP_FILE_NAME);

            System.out.println("RESULT :" + result);
            if (result) {
                infoInputLabel.setText("Code compilation successful!");
                infoInputLabel.setForeground(Color.BLUE);
                Font f = infoInputLabel.getFont();
                infoInputLabel.setFont(f.deriveFont(f.getStyle() | Font.BOLD));
            } else {
                infoInputLabel.setText("Code compilation failure. Please check your code.");
                infoInputLabel.setForeground(Color.RED);
                Font f = infoInputLabel.getFont();
                infoInputLabel.setFont(f.deriveFont(f.getStyle() | Font.BOLD));
            }
        }
    }//GEN-LAST:event_verifyCodeBtnActionPerformed

    private void compileCodeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compileCodeBtnActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_compileCodeBtnActionPerformed

    private void TokenizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TokenizeActionPerformed
        // TODO add your handling code here:

        fileAsString = cCodeTextArea.getText();
        if (!fileAsString.isEmpty()) {
            try {
                Tokenizer mTokenizer = new Tokenizer(fileAsString);
                
                cCodeTextArea.setText(mTokenizer.reduceBlanksToOne());
                cCodeTextArea.setText(mTokenizer.removeIncludesAndComments());
                
                // mTokenizer.parseIntegerVariables();
                
                // mTokenizer.parseOperations();
                
               cCodeTextArea.setText(mTokenizer.parseMainFunction());
                
                String optimized = cCodeTextArea.getText();
                
                LexInter li = new LexInter();
                Assembly assemb = new Assembly(li);
                Lexer lex = new Lexer(optimized);
                Parser parse = new Parser(lex, assemb);
                
                System.out.println("<Intermediate code>");
                parse.program();
                System.out.write('\n');
                System.out.println();
                System.out.println("<Assembly code>");
                mipsCodeTextArea.setText(assemb.program());
            } catch (IOException ex) {
                Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_TokenizeActionPerformed

    private void clearAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllBtnActionPerformed
        // TODO add your handling code here:

        cCodeTextArea.setText("");
        mipsCodeTextArea.setText("");
    }//GEN-LAST:event_clearAllBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws MalformedURLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Tokenize;
    private javax.swing.JTextArea cCodeTextArea;
    private javax.swing.JButton clearAllBtn;
    private javax.swing.JButton compileCodeBtn;
    private javax.swing.JLabel explanationLabel;
    private javax.swing.JLabel infoInputLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea mipsCodeTextArea;
    private javax.swing.JButton uploadCodeBtn;
    private javax.swing.JButton verifyCodeBtn;
    // End of variables declaration//GEN-END:variables
}
